apiVersion: v1
kind: Service
metadata:
  name: member-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 4002
    - name: tcp
      port: 5002
      targetPort: 5002
  selector:
    app: member-service
