apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service
  labels:
    app: member-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-service
  template:
    metadata:
      labels:
        app: member-service
    spec:
      containers:
        - name: member-service
          image: saihu-acr-registry-vpc.cn-hongkong.cr.aliyuncs.com/dev/member-service:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 4002
            - containerPort: 5002
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4002
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4002
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
          envFrom:
            - secretRef:
                name: member-service-secret
