# ── 1. External HTTP traffic (port 4002 → /healthz) ────────────────
apiVersion: v1
kind: Service
metadata:
  name: member-service
spec:
  type: ClusterIP
  selector:
    app: member-service
  ports:
    - name: http
      port: 80
      targetPort: 4002
---
# ── 2. In-cluster raw-TCP endpoint (port 5002) ─────────────────────
apiVersion: v1
kind: Service
metadata:
  name: member-service-tcp
spec:
  clusterIP: None
  selector:
    app: member-service
  ports:
    - name: tcp-micro
      port: 5002
      targetPort: 5002
