# ── 1. External HTTP traffic only (port 4008 → /healthz) ───────────
apiVersion: v1
kind: Service
metadata:
  name: order-service # keeps the original DNS / external LB name
  annotations:
    # Tell Alibaba Cloud SLB to probe ONLY the HTTP port
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-health-check-type: 'http'
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-health-check-uri: '/healthz'
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-health-check-connect-port: '4008'
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
    - name: http
      port: 80
      targetPort: 4008
---
# ── 2. In-cluster raw-TCP micro-service endpoint (port 5008) ───────
apiVersion: v1
kind: Service
metadata:
  name: order-service-tcp
spec:
  clusterIP: None
  selector:
    app: order-service
  ports:
    - name: tcp-micro
      port: 5008
      targetPort: 5008
