# ── 1. External HTTP traffic only (port 4008 → /healthz) ───────────
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - name: http
      port: 80
      targetPort: 4008
---
# ── 2. In-cluster raw-TCP micro-service endpoint (port 5008) ───────
apiVersion: v1
kind: Service
metadata:
  name: order-service-tcp
spec:
  clusterIP: None
  selector:
    app: order-service
  ports:
    - name: tcp-micro
      port: 5008
      targetPort: 5008
